# Generated by Django 5.1.7 on 2025-12-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pelatihan', '0002_modelstorage'),
        ('prediksi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPelatihanInfo',
            fields=[
            ],
            options={
                'verbose_name': 'Data Pelatihan (Info Data)',
                'verbose_name_plural': 'Data Pelatihan (Info Data)',
                'db_table': 'data_pelatihan',
                'managed': False,
                'proxy': True,
            },
            bases=('pelatihan.datapelatihan',),
        ),
        migrations.CreateModel(
            name='PrediksiGayaBelajarInfo',
            fields=[
            ],
            options={
                'verbose_name': 'Prediksi Gaya Belajar (Info)',
                'verbose_name_plural': 'Prediksi Gaya Belajar (Info)',
                'db_table': 'prediksi_prediksigayabelajar',
                'managed': False,
                'proxy': True,
            },
            bases=('prediksi.prediksigayabelajar',),
        ),
    ]
