# Generated by Django 5.1.7 on 2025-10-01 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prediksi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediksiGayaBelajarAdmin',
            fields=[
                ('prediksigayabelajar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prediksi.prediksigayabelajar')),
            ],
            options={
                'db_table': 'prediksi_prediksigayabelajar',
                'managed': False,
            },
            bases=('prediksi.prediksigayabelajar',),
        ),
        migrations.CreateModel(
            name='GayaBelajarAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Gaya Belajar (Admin)',
                'verbose_name_plural': 'Gaya Belajar (Admin)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('prediksi.gayabelajar',),
        ),
        migrations.CreateModel(
            name='InputDataAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Data Pelatihan (Admin)',
                'verbose_name_plural': 'Data Pelatihan (Admin)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('prediksi.inputdata',),
        ),
    ]
