# Generated by Django 5.1.7 on 2025-05-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi', '0003_rename_real_target_prediksigayabelajar_id_gaya_belajar'),
    ]

    operations = [
        migrations.CreateModel(
            name='GayaBelajar',
            fields=[
                ('id_gaya_belajar', models.AutoField(primary_key=True, serialize=False)),
                ('nama_target', models.CharField(max_length=200)),
                ('gambar', models.TextField()),
            ],
            options={
                'db_table': 'gaya_belajar',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='prediksigayabelajar',
            name='id_gaya_belajar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prediksi.gayabelajar'),
        ),
    ]
