# Generated by Django 5.1.7 on 2025-12-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelatihan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_model', models.CharField(default='model_nb', max_length=100)),
                ('model_blob', models.BinaryField(null=True)),
                ('selected_features', models.BinaryField(null=True)),
                ('split_data', models.BinaryField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
