# Generated by Django 5.1.7 on 2025-10-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GayaBelajar',
            fields=[
                ('id_gaya_belajar', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_target', models.CharField(max_length=100)),
                ('gambar', models.ImageField(upload_to='gambar_gaya_belajar/')),
            ],
            options={
                'db_table': 'gaya_belajar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id_pelatihan', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('jenis_kelamin', models.CharField(max_length=200)),
                ('jurusan', models.CharField(max_length=200)),
                ('P1', models.IntegerField()),
                ('P2', models.IntegerField()),
                ('P3', models.IntegerField()),
                ('P4', models.IntegerField()),
                ('P5', models.IntegerField()),
                ('P6', models.IntegerField()),
                ('P7', models.IntegerField()),
                ('P8', models.IntegerField()),
                ('P9', models.IntegerField()),
                ('P10', models.IntegerField()),
                ('P11', models.IntegerField()),
                ('P12', models.IntegerField()),
                ('P13', models.IntegerField()),
                ('P14', models.IntegerField()),
                ('P15', models.IntegerField()),
                ('real_target', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'data_pelatihan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrediksiGayaBelajar',
            fields=[
                ('id_prediksi', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('usia', models.CharField(max_length=3)),
                ('jenis_kelamin', models.CharField(max_length=200)),
                ('kelas', models.CharField(max_length=200)),
                ('jurusan', models.CharField(max_length=200)),
                ('asal_sekolah', models.CharField(max_length=200)),
                ('P1', models.IntegerField()),
                ('P2', models.IntegerField()),
                ('P3', models.IntegerField()),
                ('P4', models.IntegerField()),
                ('P5', models.IntegerField()),
                ('P6', models.IntegerField()),
                ('P7', models.IntegerField()),
                ('P8', models.IntegerField()),
                ('P9', models.IntegerField()),
                ('P10', models.IntegerField()),
                ('P11', models.IntegerField()),
                ('P12', models.IntegerField()),
                ('P13', models.IntegerField()),
                ('P14', models.IntegerField()),
                ('P15', models.IntegerField()),
            ],
            options={
                'db_table': 'prediksi_prediksigayabelajar',
                'managed': False,
            },
        ),
    ]
