# Generated by Django 5.1.7 on 2025-05-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi', '0002_inputdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediksigayabelajar',
            old_name='real_target',
            new_name='id_gaya_belajar',
        ),
    ]
