# Generated by Django 5.1.7 on 2025-05-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi', '0004_gayabelajar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGambar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gaya_belajar', models.IntegerField()),
                ('nama_target', models.CharField(max_length=100)),
                ('gambar', models.BinaryField()),
            ],
            options={
                'db_table': 'gaya_belajar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='gaya_belajar',
            fields=[
                ('id_gaya_belajar', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_target', models.CharField(max_length=100)),
                ('gambar', models.ImageField(upload_to='gambar_gaya_belajar/')),
            ],
            options={
                'db_table': 'gaya_belajar',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='GayaBelajar',
        ),
        migrations.AlterModelOptions(
            name='prediksigayabelajar',
            options={'managed': False},
        ),
    ]
