# Generated by Django 5.1.7 on 2025-09-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi', '0005_datagambar_gaya_belajar_delete_gayabelajar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataGambar',
        ),
        migrations.AlterModelTable(
            name='prediksigayabelajar',
            table='prediksi_prediksigayabelajar',
        ),
    ]
